### PR TITLE
Update td3.py

### PR DESCRIPTION
**Pull request by dapatil211**
The critic loss function wasn't being used

### CODE REVIEW

**Review by sriyash421 — DISMISSED** [review]

**Review by sriyash421 — COMMENTED** [review]
Given that distributional networks are gaining some traction now, should we test the implementation with distributional value functions?

**Review by alirahkay — APPROVED** [review]
LGTM.

**Comment by dapatil211** [comment]
@sriyash421 I am confused, is your comment with respect to the current PR?

**Comment by sriyash421** [comment]
@dapatil211 yes. I think I didnt make it clear. My main doubt was that can the td3 agent directly support distributional RL if I make changes  in the config; network and loss_fn mainly?

**Comment by dapatil211** [comment]
Unlikely, a distributional agent needs to be able to access and separately handle the distribution over the action space as well as the actions themselves. See the changes made to the rainbow agent. Either way, it's out of scope for this PR.

**Review by sriyash421 — APPROVED** [review]

**Pull request merged**
